version: '2'
services:
  web:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile.server
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
  monitor:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile.worker
    ports:
     - "5555:5555"
    entrypoint: celery
    command: flower -A tasks --port=5555 --loglevel=info
    depends_on:
      - redis
  redis:
    image: redis