
FROM ubuntu:16.04


RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3-pip python-dev
RUN apt-get install -y octave

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true


# copy source code
COPY . /flask-celery
WORKDIR /flask-celery

# install requirements
RUN pip3 install -r requirements.txt


# run the worker
ENTRYPOINT celery -A tasks worker --loglevel=info